# Generated by Django 5.2.6 on 2025-09-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('description_html', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('keywords', models.CharField(blank=True, help_text='Separadas por coma: aventura, ciencia ficción, etc.', max_length=300)),
                ('detail_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
